### ISSUE TITLE
Runs only on default branch

### ISSUE THREAD

**Issue by rohan20** [deepakputhraya/action-pr-title#17]
This might be more of a github-actions question than an issue with this action. I'm new to github-actions so would appreciate some help :) 

This is the `yml` script that I use but it triggers only on PRs based on the `master` (default) branch. When I open a PR on a `release/...` branch, this is not triggered. I assumed that if I don't specifically set a branch under the `on:` condition, it should work for all branches. Is that not the case? 

```
name: PR Title Check

on:
  pull_request:
    types: [ opened, edited, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Pull Request title rules
        uses: deepakputhraya/action-pr-title@v1.0.2
        with:
          regex: {redacted}
```
