### ISSUE TITLE
Regex validation isnt working properly

### ISSUE THREAD

**Issue by AllanOricil** [deepakputhraya/action-pr-title#21]
I have the following workflow

````yml
validate-pr-title:
        name: PR Title Validation
        runs-on: ubuntu-latest
        steps:
          - uses: deepakputhraya/action-pr-title@master
            with:
              regex: '((feature|bugfix|hotfix)\/){0,1}(MULE|HUG)-\d+'
              prefix_case_sensitive: true
              github_token: ${{ github.token }}

````

This is the output of the job:

![image](https://user-images.githubusercontent.com/55927613/165737237-8b608b7d-68e1-4ca8-952b-9dc435f86a82.png)

This is what it should have done
![image](https://user-images.githubusercontent.com/55927613/165737521-563cd3eb-8c93-4cfd-ad02-4c3d72ee1eb3.png)

Why isn't it failing if the PR title does not match the regex?
https://github.com/deepakputhraya/action-pr-title/blob/3864bebc79c5f829d25dd42d3c6579d040b0ef16/index.js#L43-L47
